version: "3.8"

x-node: &node
  image: ${IMAGE-analythium/python-shiny-lb:0.1}
  restart: always
  expose:
    - "8080"

services:

  node1:
    <<: *node
  node2:
    <<: *node
  node3:
    <<: *node

  caddy:
    image: caddy:2.4.6-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile-lb:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - node1
      - node2
      - node3
    environment:
      - HOST=":80"
      - LB_POLICY=${LB_POLICY-ip_hash}

volumes:
  caddy_data:
  caddy_config:
