FROM eddelbuettel/r2u:22.04

RUN install.r shiny rmarkdown bslib

RUN addgroup --system app && adduser --system --ingroup app app
WORKDIR /home/app
COPY load-balancing-r .
RUN chown app:app -R /home/app
USER app

EXPOSE 8080

CMD ["R", "-e", "shiny::runApp('/home/app', port = 8080, host = '0.0.0.0')"]