FROM python:3.9
COPY load-balancing/requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt
WORKDIR app
COPY load-balancing .
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]
